version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["cb:70:e2:cf:b8:75:1e:30:70:3b:bc:3e:78:93:cc:27"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            pwd && \
            ls -la && \
            cat inventory && \
            ansible-playbook -i inventory playbook.yml
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
