version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["52:8b:2f:34:cc:79:b5:d7:0d:af:c1:57:8f:d4:aa:31","2e:c7:a9:a5:ec:b8:94:b0:74:1e:c6:0a:1a:b1:02:00"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            pwd && \
            ls -la && \
            cat inventory && \
            chmod 400 *.pem && \
            ls -la && \
            ansible-playbook -i inventory playbook.yml --private-key udacity_CICD.pem

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
